// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/iraca.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulate
Rcpp::DataFrame simulate(int nDays, std::vector<std::vector<float>> demographicData, std::vector<std::vector<float>> temperatureData, std::vector<std::vector<float>> movementData, int incubationPeriod, int infectionDuration, float initInfectedHumans, float initInfectedMosquitoes);
RcppExport SEXP _iraca_simulate(SEXP nDaysSEXP, SEXP demographicDataSEXP, SEXP temperatureDataSEXP, SEXP movementDataSEXP, SEXP incubationPeriodSEXP, SEXP infectionDurationSEXP, SEXP initInfectedHumansSEXP, SEXP initInfectedMosquitoesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nDays(nDaysSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<float>> >::type demographicData(demographicDataSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<float>> >::type temperatureData(temperatureDataSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<float>> >::type movementData(movementDataSEXP);
    Rcpp::traits::input_parameter< int >::type incubationPeriod(incubationPeriodSEXP);
    Rcpp::traits::input_parameter< int >::type infectionDuration(infectionDurationSEXP);
    Rcpp::traits::input_parameter< float >::type initInfectedHumans(initInfectedHumansSEXP);
    Rcpp::traits::input_parameter< float >::type initInfectedMosquitoes(initInfectedMosquitoesSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate(nDays, demographicData, temperatureData, movementData, incubationPeriod, infectionDuration, initInfectedHumans, initInfectedMosquitoes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iraca_simulate", (DL_FUNC) &_iraca_simulate, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_iraca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
