# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title run simulation
#' @param nDays Number of days to simulate.
#' @param demographicData Data frame containing the Demographic data for the
#' synthetic population.
#' @param temperatureData Data frame with the temperature historic.
#' @param movementData Data frame with the movement flow between territories.
#' @param incubationPeriod Incubation period of the disease.
#' @param infectionDuration Infection duration of the disease.
#' @param initInfectedHumans Percentage of initially infected humans.
#' @param initInfectedMosquitoes Percentage of initially infected mosquitoes.
#' @param geometries Geometries as text.
#' @return Dataframe with susceptible, infected an recovered individuals each
#' day
#' @keywords internal
internal_simulation_cpp <- function(nDays, demographicData, temperatureData, movementData, incubationPeriod, infectionDuration, initInfectedHumans, initInfectedMosquitoes, geometries) {
    .Call(`_iraca_internal_simulation_cpp`, nDays, demographicData, temperatureData, movementData, incubationPeriod, infectionDuration, initInfectedHumans, initInfectedMosquitoes, geometries)
}

testGeometry <- function(wkt_t2) {
    invisible(.Call(`_iraca_testGeometry`, wkt_t2))
}

