# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Test fun
#' @param n Integer for the last element in the sequence
#' @export
get_numbers <- function(n) {
    .Call(`_iraca_get_numbers`, n)
}

#' @title run simulation
#' @param n_days number of days to simulate
#' @export
run_simulation <- function(n_days = 365L) {
    invisible(.Call(`_iraca_run_simulation`, n_days))
}

