# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Test fun
#' @export
get_numbers <- function(n) {
    .Call(`_iraca_get_numbers`, n)
}

